### ISSUE TITLE
mdl is not being required through webpack.

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#17]
Even though mdl is in the project dependencies, the css styles are being loaded into the site with a <link>tag, instead of being required through webpack.

**Comment by MrCeleryman** [comment]
Do you know how to set it up with webpack or do you need help?

**Comment by CaptainAchilles** [comment]
I know how to do all this, was just lazy when intially doing it.

I think using [Vue Material](https://vuematerial.github.io/) is the way to go instead of mdl though

**Comment by MrCeleryman** [comment]
Wow Vue Material looks amazing, are you able to implement it?

**Comment by CaptainAchilles** [comment]
Easily
