### ISSUE TITLE
Code style and linting

### ISSUE THREAD

**Issue by MrCeleryman** [MrCeleryman/Parmyay#20]
I think as our project grows and more people join us we should implement a common code style and add a linter like eslint or tslint

**Comment by CaptainAchilles** [comment]
I feel as though we need to determine a style guide that the team agrees on. Using a standard one, such as google's is a good place to start, and we can possibly tweak it to suit our own styles and preferences.

**Comment by MrCeleryman** [comment]
closed by #24
