### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#21]
Unit testing would be useful to include in the project.

Vue recommends [Karma](https://karma-runner.github.io/1.0/index.html) which contains some examples in the documentation.

**Comment by MrCeleryman** [comment]
I will look into frameworks for go as well

**Comment by MrCeleryman** [comment]
I setup testing in go with #32, I may need some help with setting up mocha or jest with vue though @CaptainAchilles

**Comment by CaptainAchilles** [comment]
I am happy to look into unit testing for the Vue modules 🎉

**Comment by CaptainAchilles** [comment]
This really cool github project basically does what we want it to in terms of testing: https://github.com/CaptainAchilles/vue-typescript-webpack

The tests are even written in typescript and run the Vue components through webpack to get code coverage reports for it.

**Comment by MrCeleryman** [comment]
I will close this issue and move it to ParmyayWeb seeing as testing has been setup for the API
