### ISSUE TITLE
Use underscores for received JSON because they are better

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#27]
See attatched.
![Bug](http://static.fjcdn.com/gifs/Lizard+laugh+gif+version+huerhuerhueruheruheruheruhrr_0021b3_5181522.gif)

**Comment by MrCeleryman** [comment]
Closing for being no constructive.

see attached.

![Yea Nah](http://i.imgur.com/OTNkm.png)
