### ISSUE TITLE
Implement Mockups

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#3]
Cheers mate

![home](https://cloud.githubusercontent.com/assets/16090868/23828489/dcaf6a5a-071e-11e7-9892-012d2f5a691f.JPG)
![map](https://cloud.githubusercontent.com/assets/16090868/23828490/dde23524-071e-11e7-937e-c08c9f311e16.JPG)

**Comment by JonathanHolland** [comment]
I'll be replacing these abominations with something functional from balsamiq in the next few days, then working on the UI a bit

**Comment by MrCeleryman** [comment]
Any updates on your progress @JonathanHolland Would love to see what you have come up with 💯

**Comment by CaptainAchilles** [comment]
ParmyayWeb and ParmyayMobile have their own issues for this.
