### ISSUE TITLE
Couple npm run build... more tightly with compilation of go

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#34]

**Comment by MrCeleryman** [comment]
How do you mean? what else could there be done?

**Comment by CaptainAchilles** [comment]
Integrating the installation of go is entirely possible with npm, I am looking into a nice way to wrap it around `gcc` as well, so that go doesn't need to be installed globally.

**Comment by MrCeleryman** [comment]
the only thing that needs gcc is sqlite for go. but yes I think integrating the whole installation process would make the set up a lot easier, looking forward to seeing your progress on this. If you need a hand just ask 💯

**Comment by CaptainAchilles** [comment]
As per our offline discussions:
"GO should be more of its own thing than the parmyay. Since it is an API it should be consumed by a client, and the API should be separated from the main project. This leaves a path for the future to move the API into its own repo. The GO and GCC installs should be a perquisite of the project. The GO build will be automated for now with `npm run build` or `npm run dev`, but only if the prerequisites are detected."
