### ISSUE TITLE
Shims for es compatibility.

### ISSUE THREAD

**Issue by CaptainAchilles** [MrCeleryman/Parmyay#39]
Our project is targeting es6, however we have no shims in place for older browsers. I think it is appropriate to use something like the following to preserve backwards compatibility for our application.

https://www.npmjs.com/package/es6-shim
https://www.npmjs.com/package/es5-shim

**Comment by MrCeleryman** [comment]
does vue typescript work with es6?

**Comment by CaptainAchilles** [comment]
Absolutely!
I just realised that our project is targetting es5, but with an "es6" as a lib. 

I changed the target to "es6", and everything still built fine.

The point I am trying to make though is that if we use es6 features and the browser doesn't natively support it, then it will break on the client. Typescript doesn't magically implement things like `find` for us, which is why I think shims are necessary, or adjustments to the linter to warn of es6 features.

**Comment by MrCeleryman** [comment]
So like babel?

**Comment by CaptainAchilles** [comment]
Only in the sense that typescript converts its own syntax to JavaScript. Babel converts later versions of Javascript syntax to older versions. Neither Babel nor Typescript will make your code magically work on older machines without a shim or polyfill.

**Comment by MrCeleryman** [comment]
Yea I'm suggesting using babel polyfills

**Comment by CaptainAchilles** [comment]
As per our offline discussion:
"Babel polyfills are a bit more bloated than the es shims, and they will be a bit harder to integrate into the project. If the time arises when there is a more signifcant benefit for using babel polyfills we can investigate how to get it into the project".

Implementing es5 and es6 shims for now.

**Comment by CaptainAchilles** [comment]
I think that if we do use babel, and babel-polyfill we can run it against the tests to allow for es syntax in our testing framework

**Comment by CaptainAchilles** [comment]
Moved to https://github.com/MrCeleryman/ParmyayWeb/issues/3
