### ISSUE TITLE
Move the web component of Parmyay to its own repo

### ISSUE THREAD

**Issue by MrCeleryman** [MrCeleryman/Parmyay#44]
As discussed in the [ParmyayMobile repo](https://github.com/MrCeleryman/Parmyaymobile/issues/3#)
We will be moving the web component of Parmyay to its own Repo name ParmyayWeb as we now have a ParmyayMobile repo

Once the merge has been made all open issues relating to the web component will be move there and any other possible conversions will also be made

**Comment by CaptainAchilles** [comment]
I'll do this tonight

**Comment by MrCeleryman** [comment]
Any progress updated on this one?
